"""Deterministic disposable Markdown views derived from authored OKF state."""

from __future__ import annotations

import json
from collections import defaultdict
from datetime import date
from pathlib import Path
from typing import TYPE_CHECKING

from okf_parser.bundle import load_bundle

if TYPE_CHECKING:
    from collections.abc import Sequence

_GENERATED = "<!-- GENERATED FILE — DO NOT EDIT. Regenerate with okf-parser materialize. -->"
_DATE_KEYS = ("updated", "date", "created")
_IGNORE_LINES = ("/index.md", "/log.md")


def _display_title(row: dict[str, object]) -> str:
    title = row.get("title")
    if isinstance(title, str) and title.strip():
        return title.strip()
    logical_key = row.get("logical_key")
    return str(logical_key)


def render_index(path: Path, exclude: Sequence[str] = ()) -> str:
    """Render a deterministic concept index grouped by producer-defined type."""
    bundle = load_bundle(path, exclude)
    rows = bundle.concepts.order_by("concept_type", "logical_key").execute().to_dict(orient="records")
    grouped: dict[str, list[dict[str, object]]] = defaultdict(list)
    for row in rows:
        grouped[str(row["concept_type"])].append(row)

    lines = [_GENERATED, "", "# Index", ""]
    for concept_type in sorted(grouped, key=str.casefold):
        lines.extend((f"## {concept_type}", ""))
        for row in grouped[concept_type]:
            title = _display_title(row).replace("[", "\[").replace("]", "\]")
            target = str(row["path"]).replace(" ", "%20")
            lines.append(f"- [{title}]({target})")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _frontmatter_date(row: dict[str, object]) -> str | None:
    raw = row.get("frontmatter_json")
    if not isinstance(raw, str):
        return None
    frontmatter = json.loads(raw)
    for key in _DATE_KEYS:
        value = frontmatter.get(key)
        if not isinstance(value, str):
            continue
        try:
            parsed = date.fromisoformat(value)
        except ValueError:
            continue
        if parsed.isoformat() == value:
            return value
    return None


def render_log(path: Path, exclude: Sequence[str] = ()) -> str:
    """Render dated concepts newest first without consulting Git or filesystem mtimes."""
    bundle = load_bundle(path, exclude)
    rows = bundle.concepts.execute().to_dict(orient="records")
    dated: dict[str, list[dict[str, object]]] = defaultdict(list)
    for row in rows:
        authored_date = _frontmatter_date(row)
        if authored_date is not None:
            dated[authored_date].append(row)

    lines = [_GENERATED, "", "# Log", ""]
    for authored_date in sorted(dated, reverse=True):
        lines.extend((f"## {authored_date}", ""))
        for row in sorted(dated[authored_date], key=lambda item: str(item["logical_key"])):
            title = _display_title(row).replace("[", "\[").replace("]", "\]")
            target = str(row["path"]).replace(" ", "%20")
            concept_type = str(row["concept_type"])
            lines.append(f"- [{title}]({target}) — {concept_type}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _ensure_gitignore(root: Path) -> bool:
    path = root / ".gitignore"
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    existing_lines = {line.strip() for line in existing.splitlines()}
    missing = [line for line in _IGNORE_LINES if line not in existing_lines]
    if not missing:
        return False
    prefix = existing
    if prefix and not prefix.endswith("\n"):
        prefix += "\n"
    if prefix and not prefix.endswith("\n\n"):
        prefix += "\n"
    path.write_text(
        prefix
        + "# Disposable views generated by okf-parser at runtime\n"
        + "\n".join(missing)
        + "\n",
        encoding="utf-8",
    )
    return True


def materialize_derived_views(
    path: Path,
    exclude: Sequence[str] = (),
    *,
    write: bool = True,
    update_gitignore: bool = True,
) -> dict[str, object]:
    """Generate index/log projections, optionally writing them to the bundle root."""
    root = path.resolve()
    index = render_index(root, exclude)
    log = render_log(root, exclude)
    gitignore_changed = False
    written: list[str] = []
    if write:
        (root / "index.md").write_text(index, encoding="utf-8")
        (root / "log.md").write_text(log, encoding="utf-8")
        written.extend(("index.md", "log.md"))
        if update_gitignore:
            gitignore_changed = _ensure_gitignore(root)
    return {
        "root": str(root),
        "generated": {"index.md": index, "log.md": log},
        "written": written,
        "gitignore_changed": gitignore_changed,
        "source_of_truth": "okf",
    }
