"""Export JSON Schema and Zod schema definitions for OKF concepts."""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING, Any

from okf_parser.bundle import load_bundle

if TYPE_CHECKING:
    from collections.abc import Sequence


def _infer_type_from_value(value: Any) -> dict[str, Any]:
    if isinstance(value, bool):
        return {"type": "boolean"}
    if isinstance(value, int):
        return {"type": "integer"}
    if isinstance(value, float):
        return {"type": "number"}
    if isinstance(value, list):
        if value:
            item_schema = _infer_type_from_value(value[0])
            return {"type": "array", "items": item_schema}
        return {"type": "array", "items": {"type": "string"}}
    if isinstance(value, dict):
        properties = {k: _infer_type_from_value(v) for k, v in value.items()}
        return {"type": "object", "properties": properties}
    return {"type": "string"}


def export_json_schema(path: str, exclude: Sequence[str] = ()) -> dict[str, Any]:
    """Inspect an OKF bundle and infer a JSON Schema for every concept type."""
    bundle = load_bundle(Path(path), exclude)
    df_concepts = bundle.concepts.to_pandas()

    schemas_by_type: dict[str, dict[str, Any]] = {}

    for _, row in df_concepts.iterrows():
        ctype = str(row.get("concept_type", "concept"))
        frontmatter_raw = row.get("frontmatter_json", "{}")

        try:
            frontmatter = json.loads(frontmatter_raw) if isinstance(frontmatter_raw, str) else frontmatter_raw
        except Exception:
            frontmatter = {}

        if not isinstance(frontmatter, dict):
            frontmatter = {}

        if ctype not in schemas_by_type:
            schemas_by_type[ctype] = {
                "$schema": "https://json-schema.org/draft/2020-12/schema",
                "title": f"{ctype.capitalize()}Concept",
                "type": "object",
                "properties": {
                    "type": {"type": "string", "const": ctype},
                    "title": {"type": "string"},
                    "description": {"type": "string"},
                },
                "required": ["type"],
            }

        properties = schemas_by_type[ctype]["properties"]
        for key, val in frontmatter.items():
            if key not in properties:
                properties[key] = _infer_type_from_value(val)

    return {
        "root": str(bundle.root),
        "total_types": len(schemas_by_type),
        "schemas": schemas_by_type,
    }


def _json_schema_to_zod(prop_schema: dict[str, Any]) -> str:
    stype = prop_schema.get("type", "string")
    if prop_schema.get("const"):
        return f"z.literal({json.dumps(prop_schema['const'])})"
    if stype == "boolean":
        return "z.boolean().optional()"
    if stype == "integer":
        return "z.number().int().optional()"
    if stype == "number":
        return "z.number().optional()"
    if stype == "array":
        item_type = _json_schema_to_zod(prop_schema.get("items", {"type": "string"}))
        if item_type.endswith(".optional()"):
            item_type = item_type[:-11]
        return f"z.array({item_type}).optional()"
    if stype == "object":
        inner_props = prop_schema.get("properties", {})
        inner_zod = ", ".join(f"{k}: {_json_schema_to_zod(v)}" for k, v in inner_props.items())
        return f"z.object({{ {inner_zod} }}).optional()"
    return "z.string().optional()"


def export_zod_schema(path: str, exclude: Sequence[str] = ()) -> str:
    """Generate Zod schema definitions for Astro Content Collections."""
    json_schemas = export_json_schema(path, exclude)["schemas"]

    lines = [
        "// Generated by okf-parser",
        "import { z } from 'astro:content';",
        "",
    ]

    for ctype, schema in json_schemas.items():
        var_name = "".join(part.capitalize() for part in ctype.replace("-", "_").split("_")) + "Schema"
        props = schema.get("properties", {})

        zod_props = []
        for key, prop_def in props.items():
            zod_code = _json_schema_to_zod(prop_def)
            zod_props.append(f"  {key}: {zod_code}")

        lines.append(f"export const {var_name} = z.object({{")
        lines.append(",\n".join(zod_props))
        lines.append("});")
        lines.append("")

    return "\n".join(lines)
